### ISSUE TITLE
AddShipment werkt niet bij me

### ISSUE THREAD

**Issue by KoenWijnstok** [janssenr/MyParcelApi.Net#1]
Ik ben bezig om in vb.net iets in combinatie met onze webshop en MyParcel te knutselen.
Nu krijg ik Addshipment absoluut niet voor elkaar. Volgens mij heb ik alles goed staan, maar op het moment dat ik het ShipmentObject uit probeer te lezen gebeurt er helemaal niets. Ik krijg vanaf dat moment geen enkele feedback meer vanuit een MsgBox. Ik heb het idee dat ik ergens iets vergeten ben of iets dergelijks, maar ik krijg het niet gevonden. Dit bezorgd me al dagen hoofdpijn....
Zou je eens een oog eroverheen kunnen laten vallen om te kijken of je iets kunt vinden wat ik fout heb gedaan? 
Van Msgbox("4") krijg ik nog een melding, maar de regel erna gewoon niet.
Met GetShipment heb ik geen enkel probleem overigens, die geeft meteen shipments terug.

`
Dim Ontvanger As New Address
            Ontvanger.City = "Oisterwijk"
            ontvanger.PostalCode = "5061AS"
            ontvanger.Person = "Yada Yada"
            ontvanger.Street = "t Seuverick"
            ontvanger.Number = "12"
            ontvanger.Country = "NL"

            Dim Verzender As New Address
            Verzender.City = "Oisterwijk"
            verzender.PostalCode = "5061AS"
            verzender.Person = "Yada Yada"
            verzender.Street = "t Seuverick"
            verzender.Number = "12"
            verzender.Country = "NL"

            Dim Pakketopties As New ShipmentOptions
            Pakketopties.PackageType = PackageType.Package
            Pakketopties.LabelDescription = "Test zending"
            Pakketopties.OnlyRecipient = False
            Pakketopties.Signature = False
            Pakketopties.Return = False
            Pakketopties.LargeFormat = False
            Pakketopties.DeliveryType = DeliveryType.Standard

            Dim Verzending As New Shipment
            Verzending.Sender = verzender
            Verzending.Recipient = ontvanger
            Verzending.Options = Pakketopties
            Verzending.Carrier = Carrier.PostNl

            MsgBox("3")

            Dim MyparcelShipment As New List(Of Shipment)
            MyparcelShipment.Add(Verzending)

            Dim ShipmentObject() As ObjectId
            ShipmentObject = Await MyParcelClient.AddShipment(MyparcelShipment.ToArray())

            MsgBox("4")
            MsgBox("aantal: " & ShipmentObject.Count)

            Dim teller As Integer
            teller = 0
            For Each Id In ShipmentObject
                MsgBox("ÏD: " & ShipmentObject(teller).Id)
                teller = teller + 1
            Next
            MsgBox("klaar")

`

**Comment by janssenr** [comment]
Heb je de client via NuGet geïnstalleerd?
Of de source code gedownload via GitHub.
Als ik je Source Code plak in een VB Console Application, dan wordt in deze regel "MyParcelClient" niet herkent:
``
        ShipmentObject = Await MyParcelClient.AddShipment(MyparcelShipment.ToArray())
``
Hoe is de reference naar MyParcelClient?

**Comment by KoenWijnstok** [comment]
Ik heb hem via NuGet geïnstalleerd.
Bovenin Import ik hem met:

Imports MyParcelApi.Net
Imports MyParcelApi.Net.Models
Imports System.Threading.Tasks


Vanaf dat moment krijg ik geen enkele melding dat hij niet goed zou zijn.

**Comment by KoenWijnstok** [comment]
Overigens mist deze dan ook nog:
Dim MyParcelClient = New MyParcelApiClient("[APIKEY]")

**Comment by janssenr** [comment]
Je mag schijnbaar de property "Sender" niet vullen!
Deze code werkt bij mij
`
        Dim MyParcelClient As New MyParcelApiClient(ConfigurationManager.AppSettings("ApiKey"))

        Dim Ontvanger As New Address
        Ontvanger.City = "Oisterwijk"
        Ontvanger.PostalCode = "5061AS"
        Ontvanger.Person = "Yada Yada"
        Ontvanger.Street = "t Seuverick"
        Ontvanger.Number = "12"
        Ontvanger.Country = "NL"

        'Dim Verzender As New Address
        'Verzender.City = "Oisterwijk"
        'Verzender.PostalCode = "5061AS"
        'Verzender.Person = "Yada Yada"
        'Verzender.Street = "t Seuverick"
        'Verzender.Number = "12"
        'Verzender.Country = "NL"

        Dim Pakketopties As New ShipmentOptions
        Pakketopties.PackageType = PackageType.Package
        Pakketopties.LabelDescription = "Test zending"
        Pakketopties.OnlyRecipient = False
        Pakketopties.Signature = False
        Pakketopties.Return = False
        Pakketopties.LargeFormat = False
        Pakketopties.DeliveryType = DeliveryType.Standard

        Dim Verzending As New Shipment
        'Verzending.Sender = Verzender
        Verzending.Recipient = Ontvanger
        Verzending.Options = Pakketopties
        Verzending.Carrier = Carrier.PostNl

        MsgBox("3")

        Dim MyparcelShipment As New List(Of Shipment)
        MyparcelShipment.Add(Verzending)

        Dim Response = MyParcelClient.AddShipment(MyparcelShipment.ToArray())
        Response.Wait()
        Dim ShipmentObject() As ObjectId = Response.Result

        MsgBox("4")
        MsgBox("aantal: " & ShipmentObject.Count)

        Dim teller As Integer
        teller = 0
        For Each Id In ShipmentObject
            MsgBox("ÏD: " & ShipmentObject(teller).Id)
            teller = teller + 1
        Next
        MsgBox("klaar")
`
Heb ook de Await weg gehaald en vervangen door:
`
        Dim Response = MyParcelClient.AddShipment(MyparcelShipment.ToArray())
        Response.Wait()
        Dim ShipmentObject() As ObjectId = Response.Result
`

**Comment by KoenWijnstok** [comment]
Dat is hem!

Ik had hem in z'n eigen solution gestopt en daar werkte hij meteen.
In de originele solution werkte hij dus niet....
Totdat ik de Sender uit-gecomment had, vanaf dat moment pakt hij hem netjes.
Blijkbaar slikt hij het dus niet als de Sender ingevuld is (of misschien een andere waarde heeft dan bij Myparcel ingevuld staat?)

Joepie!
Thanks man.....
