### ISSUE TITLE
Pickups for Belgium requires location_code

### ISSUE THREAD

**Issue by FabianZoon** [janssenr/MyParcelApi.Net#10]
MyParcelApi.Net.Models.PickupLocations 
contains the properties: City, LocationName, Number, PostalCode and Street.
But the properties Location_code and retail_network_id are missing.

The Location_code is required for pickup locations in Belgium

see for more information: https://myparcelnl.github.io/api/#7_O_1

**Comment by janssenr** [comment]
Added LocationCode and RetailNetworkId to PickupLocation object
