### ISSUE TITLE
De tekenreeks is niet als geldige DateTime herkend

### ISSUE THREAD

**Issue by mrfatmen** [janssenr/MyParcelApi.Net#12]
Goedemorgen,

Is het mogelijk dat er een wijziging is in de API vanuit MyParcel.
Krijg nu meerdere melding van onderstaande foutmelding.

`De tekenreeks is niet als geldige DateTime herkend.
Source: mscorlib
Stack Trace:    bij System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   bij ReadShipmentFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bij System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   bij ReadArrayOfShipmentFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   bij System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   bij ReadDataWrapperFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bij System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   bij ReadApiWrapperFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bij System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bij System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bij System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bij System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bij System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
TargetSite: System.DateTime ParseExact(System.String, System.String, System.Globalization.DateTimeFormatInfo, System.Globalization.DateTimeStyles)

# # # # # # # # # INNER EXCEPTION
Er is een fout opgetreden bij het deserialiseren van het object van type MyParcelApi.Net.Wrappers.ApiWrapper. De tekenreeks is niet als geldige DateTime herkend.
Source: System.Runtime.Serialization
Stack Trace:    bij System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bij System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bij MyParcelApi.Net.Helpers.JsonHelper.Deserialize[T](String json, String dateTimeFormat)
   bij MyParcelApi.Net.MyParcelApiClient.<GetShipment>d__10.MoveNext()
TargetSite: System.Object ReadObjectHandleExceptions(System.Runtime.Serialization.XmlReaderDelegator, Boolean, System.Runtime.Serialization.DataContractResolver)

# # # # # # # # # OUTER EXCEPTION
Er zijn één of meer fouten opgetreden.
Source: mscorlib
Stack Trace:    bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij automate.viewmodel.VerzendFuncties.Verzenden_MyParcel(dialogVerzendenEdit Verzenden, Verzending v, String Instellingen, VerzendInfo VerzInfo)
   bij automate.viewmodel.VerzendFuncties.Verzenden(Context EFContext, Factuur CurrentFactuur, List`1 DeelVerzendingLijst, Verzending& Verzending, VerzendInfo& VerzInfo)
   bij automate.viewmodel.FactuurEdit.<Verzenden>d__244.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: TResult GetResultCore(Boolean)

Stacktrace: ExceptionWrapper.TryCatchWhen => Dispatcher.CatchException => App.ApplicationDispatcherUnhandledException
Callsite: automate.App.ApplicationDispatcherUnhandledException
Exception:`

**Comment by janssenr** [comment]
Welke functie roep je aan waaruit deze foutmelding komt?

**Comment by mrfatmen** [comment]
AddShipment

We proberen een normale verzending aan te maken.

**Comment by janssenr** [comment]
Gebruik je daarna ook een GetShipment?
Want in de GetShipment functie ging wel iets mis met de datum, maar niet bij AddShipment.

Kun je anders eens de code posten waarmee je de foutmelding krijgt?

**Comment by mrfatmen** [comment]
Je hebt helemaal gelijk.
Er worden zendingen aangemaakt met AddShipment(), daarna worden de labels opgehaald met GetShipmentLabel en GetShipment.

`            var Labels = client.AddShipment(shipments.ToArray()).Result;

            var TransNummers = new List<string>();

            foreach (var label in Labels)
            {
                byte[] Data;
                using (Stream stream = (Stream)client.GetShipmentLabel(new int[] { label.Id }, InstParcel.PapierSoort.ToString(), new int[] { Pos }).Result)
                    Data = stream.CopyAllBytes();

                string LN = string.Format("{0}.pdf", label.Id);
                var B = model.helper.BestandHelper.Toevoegen(BasisFuncties.EFContext(), LN, ref Data);
                v.Bestanden.Add(new VerzendingBestand()
                {
                    BestandId = B,
                    Extension = "PDF",
                    Orgnaam = LN,
                    Opmerking = label.Id.ToString()
                });


                string BarcodeId = label.Id.ToString();

                var info = client.GetShipment(new int[] { label.Id }).Result;
                if (info.Any() && info.First().Barcode.IsNotNullOrWhiteSpace())
                    BarcodeId = info.First().Barcode;

                TransNummers.Add(BarcodeId);
            }`

**Comment by mrfatmen** [comment]
De update welke je hebt gedaan, heeft het probleem opgelost.
Weer erg bedankt voor het bijwerken.
