### ISSUE TITLE
Please change validation of house number

### ISSUE THREAD

**Issue by davidkdb** [janssenr/MyParcelApi.Net#14]
We have an issue with the shipping.number validation you have implemented.

It should not force a numeric validation on this.

If for example a person lives in Myroad 22a, the 22a will be forbidden in your api, but probably not in MyParcel own API.

Can you please change or remove this check ?

In our case we dont even have a house number available, so we have to strip it from address.

**Comment by janssenr** [comment]
What validation are you talking about?
As far as I can see all numbers I use are string fields.
Can you provide a code example?

**Comment by davidkdb** [comment]
In this example the Shipment.Recipient.Number is set to "22a"

![image](https://user-images.githubusercontent.com/57062216/113502721-61656000-952e-11eb-84ad-ac5d4f1244d8.png)

**Comment by janssenr** [comment]
The (validation) error is from MyParcel itself. I cannot do anything about it.
You have to put "22" in Number.
And the "a" in NumberSuffix

**Comment by davidkdb** [comment]
Ok. We made a parser that handles this.
