### ISSUE TITLE
Upgrade Pickup from 1.0.13

### ISSUE THREAD

**Issue by FabianZoon** [janssenr/MyParcelApi.Net#17]
Hi,
I'm working on upgrade to the latest 1.0.16 version.

In the 1.0.13 version below was the way to create a pickup point. (still works)
 ship.Pickup = new MyParcelApi.Net.Models.PickupLocation()
            {
                City = "Amsterdam",
                Street = "Straat",
                PostalCode = "111AA",
                Number = "123",
                LocationCode = "loc1234",
                LocationName = "Albert Heijn",
                RetailNetworkId = "123"
            };

from 1.0.14 ship.Pickup is changed from a PickupLocation to a Location<string[]>
Is this correct?

**Comment by FabianZoon** [comment]
did some testing with local branche of 1.0.16 
I think the class should be mirrored from this specs https://myparcelnl.github.io/api/#7_O

**Comment by janssenr** [comment]
I updated the package to 1.0.17.
With this update I reverted the code back to:
ship.Pickup = new MyParcelApi.Net.Models.PickupLocation()
{
City = "Amsterdam",
Street = "Straat",
PostalCode = "111AA",
Number = "123",
LocationCode = "loc1234",
LocationName = "Albert Heijn",
RetailNetworkId = "123"
};

So the class mirrors https://myparcelnl.github.io/api/#7_O

**Comment by FabianZoon** [comment]
Looks great. New version works with pickup locations. Thank you for change it so quickly!
