### ISSUE TITLE
Pickup

### ISSUE THREAD

**Issue by FabianZoon** [janssenr/MyParcelApi.Net#18]
Er gaat toch iets nog niet goed in versie 1.17 met Pickup opties

Ik heb bij PickupOptions.cs [regel 14] de mapping terug moeten zetten naar "location"
en de location_code (in groene code op regel 60) weer aangezet, omdat ik die LocationCode nodig heb om een Pickup verzending aan te maken.

Als alternatief dacht ik nog om dan maar GetPickupLocationsV2 te gebruiken (ipv GetDeliveryOptions)
maar die levert geen gegevens terug (wel records, maar data is null). 
De Deserialize lijkt hier niet goed te gaan. (regel 562 van MyParcelApiClient)

Voor nu maar even een locale versie getrokken. Mocht ik moeten testen/meekijken laat het even weten.

**Comment by janssenr** [comment]
Kun je controleren of versie 1.18 wel werkt?
Ik heb nu voor een Shipment een eigen ShipmentPickupLocation object gemaakt.
En GetPickupLocationsV2 zou nu ook moeten werken.

**Comment by FabianZoon** [comment]
Ik zie inderdaad nu resultaat terugkomen bij GetPickupLocationsV2. Op het eerste gezicht lijkt dit ok. 
Kan het kloppen dat ik retail_network_id mis (pickupoptions.cs regel 17)? 
Op dit moment gebruik ik die wel en ik zie dat deze ook in de documentatie staat voor BE-pickups:
https://myparcelnl.github.io/api/#7_O

**Comment by janssenr** [comment]
https://myparcelnl.github.io/api/#7_O is het ShipmentPickupLocation object. Daarin staat (op regel 27) RetailNetworkId.
Of bedoel je dan wat anders?

**Comment by janssenr** [comment]
Ik heb LocationName en RetailNetworkId toegevoegd aan PickupOption.cs

**Comment by janssenr** [comment]
Versie 1.0.19 is nu beschikbaar via NuGet

**Comment by FabianZoon** [comment]
ja, ziet er goed uit. Code werkt (weer) bij me.
Dank voor je service.
