### ISSUE TITLE
Details van foutmelding mist

### ISSUE THREAD

**Issue by mrfatmen** [janssenr/MyParcelApi.Net#2]
Ik maak een shipment aan met een foute postcode "testPC".
Dan krijg ik een foutmelding bij de AddShipment method. "Er zijn een of meer fouten opgetreden".
Er is dan ook 1 intterExceptions maar hiervan is de message niet gevuld.

Is het mogelijk om hier ook de juiste melding bij te zetten?

**Comment by janssenr** [comment]
Als het goed is, krijg je nu ook de juiste melding mee
