### ISSUE TITLE
Serious bug in 1.0.25

### ISSUE THREAD

**Issue by davidkdb** [janssenr/MyParcelApi.Net#20]
Hi,

When we try to create the shipment, we get this error:

"Failed validation against JSON-SCHEMA shipment/post_shipments_request-v1.1.json (request_id: 1670688437.97146394aeb5ed25c)\ndata.shipments[0].delivered Boolean value found, but an integer is required\ndata.shipments[0].delivered Does not have a value in the enumeration [0]\ndata.shipments[0] The property delayed is not defined and the definition does not allow additional properties\ndata.shipments[0] The property external_identifier is not defined and the definition does not allow additional properties\ndata.shipments[0] The property link_consumer_portal is not defined and the definition does not allow additional properties"}

We have not changed anything in our code. But the data we send over is (I have xxx'ed personal info):

[{"recipient":{"cc":"BE","postal_code":"3920","city":"Lommel","street":"xxx","number":"01","number_suffix":"","person":"xxx","email":"xxx","phone":""},"options":{"only_recipient":0,"signature":0,"age_check":0,"package_type":1,"insurance":{"amount":0,"currency":"EUR"},"label_description":"xxx"},"carrier":1,"reference_identifier":"xxx","external_identifier":"xxx","delayed":false,"delivered":false,"link_consumer_portal":null}]

We reverted back to 1.0.24, and there it works.

BTW: This client is using MyParcel in Belgium

**Comment by janssenr** [comment]
Should be fixed in 1.0.26
