### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject' using TrackShipment method

### ISSUE THREAD

**Issue by david-ju** [janssenr/MyParcelApi.Net#21]
To reproduce:
_myParcelApiClient.TrackShipment(new int[] { 1 });

**Comment by janssenr** [comment]
I cannot reproduce your exception.
Do you have some more info for me?
Does for example the Add Shipment work?

Can you make code to create a shipment and then track this shipment?

I only use the Newtonsoft.Json.Linq.JObject when a error occurs.
So something is going wrong.

**Comment by david-ju** [comment]
I've downloaded the code to see what's what: the error actually occurs in the HandleResponseError method. This is the response json I get
`{"message":"Permission Denied. (readResourceOwnedByOthers) (request_id: 1684937625.4099646e1b9964132)","request_id":"1684937625.4099646e1b9964132","errors":[{"status":401,"code":3001,"title":"Permission Denied. (readResourceOwnedByOthers)","message":"Permission Denied. (readResourceOwnedByOthers)"}]}`

**Comment by janssenr** [comment]
I fixed the HandleResponseError function, so the error will not occur anymore.
But I think you pass the wrong shipmentId to the TrackShipment function.
The shipmentId is not from a shipment you created.
