### ISSUE TITLE
Carrier is not showing in the shipments endpoint

### ISSUE THREAD

**Issue by NicoJuicy** [janssenr/MyParcelApi.Net#6]
Carrier was not showing in my API-calls

- Added support for DPD in Belgium ( uses the same endpoint)
https://github.com/janssenr/MyParcelApi.Net/pull/4

- Production environment seems to be different from the documentation. Added a json example in the PR
https://github.com/janssenr/MyParcelApi.Net/pull/5

**Comment by janssenr** [comment]
Merged Pull requests
