### ISSUE TITLE
The property carrier_id is not defined and the definition does not allow additional properties

### ISSUE THREAD

**Issue by epmik** [janssenr/MyParcelApi.Net#9]
In version 1.0.10, just about any piece of code fails with the exception: 'The property carrier_id is not defined and the definition does not allow additional properties.'
Just run the unit tests and you should encounter the issue. 
The cullprit is the CarrierFallback property in the Shipment class.

**Comment by janssenr** [comment]
Fixed by changing:
        /// <summary>
        /// This is a workarround for a bug in the MyParcelApi where there is inconsistency between getting the Carriers [GET] and Creating/Updating them [POST/PUT].
        /// It's also possible to be null
        /// </summary>
        [DataMember(Name = "carrier_id", EmitDefaultValue = false, IsRequired = false)]
        private Carrier? CarrierFallback
        {
            get
            {
                //return Carrier;
                //Set to null, because of error "The property carrier_id is not defined and the definition does not allow additional properties."
                return null;
            }
            set
            {
                if (value.HasValue)
                {
                    Carrier = value.Value;
                }

            }
        }
